// Code generated by ent, DO NOT EDIT.

package searchdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the searchdocument type in the database.
	Label = "search_document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCompanyID holds the string denoting the company_id field in the database.
	FieldCompanyID = "company_id"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldDocNumber holds the string denoting the doc_number field in the database.
	FieldDocNumber = "doc_number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldTitleNative holds the string denoting the title_native field in the database.
	FieldTitleNative = "title_native"
	// FieldTitleLatin holds the string denoting the title_latin field in the database.
	FieldTitleLatin = "title_latin"
	// FieldTitleInitials holds the string denoting the title_initials field in the database.
	FieldTitleInitials = "title_initials"
	// FieldMemoNative holds the string denoting the memo_native field in the database.
	FieldMemoNative = "memo_native"
	// FieldDocDate holds the string denoting the doc_date field in the database.
	FieldDocDate = "doc_date"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldURLPath holds the string denoting the url_path field in the database.
	FieldURLPath = "url_path"
	// FieldProjectorVersion holds the string denoting the projector_version field in the database.
	FieldProjectorVersion = "projector_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the searchdocument in the database.
	Table = "search_documents"
)

// Columns holds all SQL columns for searchdocument fields.
var Columns = []string{
	FieldID,
	FieldCompanyID,
	FieldEntityType,
	FieldEntityID,
	FieldDocNumber,
	FieldTitle,
	FieldSubtitle,
	FieldTitleNative,
	FieldTitleLatin,
	FieldTitleInitials,
	FieldMemoNative,
	FieldDocDate,
	FieldAmount,
	FieldCurrency,
	FieldStatus,
	FieldURLPath,
	FieldProjectorVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EntityTypeValidator is a validator for the "entity_type" field. It is called by the builders before save.
	EntityTypeValidator func(string) error
	// DefaultDocNumber holds the default value on creation for the "doc_number" field.
	DefaultDocNumber string
	// DocNumberValidator is a validator for the "doc_number" field. It is called by the builders before save.
	DocNumberValidator func(string) error
	// DefaultSubtitle holds the default value on creation for the "subtitle" field.
	DefaultSubtitle string
	// DefaultTitleLatin holds the default value on creation for the "title_latin" field.
	DefaultTitleLatin string
	// DefaultTitleInitials holds the default value on creation for the "title_initials" field.
	DefaultTitleInitials string
	// DefaultMemoNative holds the default value on creation for the "memo_native" field.
	DefaultMemoNative string
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount string
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// URLPathValidator is a validator for the "url_path" field. It is called by the builders before save.
	URLPathValidator func(string) error
	// DefaultProjectorVersion holds the default value on creation for the "projector_version" field.
	DefaultProjectorVersion int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SearchDocument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCompanyID orders the results by the company_id field.
func ByCompanyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyID, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByDocNumber orders the results by the doc_number field.
func ByDocNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySubtitle orders the results by the subtitle field.
func BySubtitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtitle, opts...).ToFunc()
}

// ByTitleNative orders the results by the title_native field.
func ByTitleNative(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleNative, opts...).ToFunc()
}

// ByTitleLatin orders the results by the title_latin field.
func ByTitleLatin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleLatin, opts...).ToFunc()
}

// ByTitleInitials orders the results by the title_initials field.
func ByTitleInitials(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleInitials, opts...).ToFunc()
}

// ByMemoNative orders the results by the memo_native field.
func ByMemoNative(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoNative, opts...).ToFunc()
}

// ByDocDate orders the results by the doc_date field.
func ByDocDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocDate, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByURLPath orders the results by the url_path field.
func ByURLPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURLPath, opts...).ToFunc()
}

// ByProjectorVersion orders the results by the projector_version field.
func ByProjectorVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectorVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
