// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SearchDocumentsColumns holds the columns for the "search_documents" table.
	SearchDocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeUint},
		{Name: "entity_type", Type: field.TypeString, Size: 32},
		{Name: "entity_id", Type: field.TypeUint},
		{Name: "doc_number", Type: field.TypeString, Nullable: true, Size: 64, Default: ""},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "subtitle", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "title_native", Type: field.TypeString, Size: 2147483647},
		{Name: "title_latin", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "title_initials", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "memo_native", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "doc_date", Type: field.TypeTime, Nullable: true},
		{Name: "amount", Type: field.TypeString, Nullable: true, Size: 32, Default: ""},
		{Name: "currency", Type: field.TypeString, Nullable: true, Size: 3, Default: ""},
		{Name: "status", Type: field.TypeString, Nullable: true, Size: 32, Default: ""},
		{Name: "url_path", Type: field.TypeString, Size: 255},
		{Name: "projector_version", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SearchDocumentsTable holds the schema information for the "search_documents" table.
	SearchDocumentsTable = &schema.Table{
		Name:       "search_documents",
		Columns:    SearchDocumentsColumns,
		PrimaryKey: []*schema.Column{SearchDocumentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "searchdocument_company_id_entity_type_entity_id",
				Unique:  true,
				Columns: []*schema.Column{SearchDocumentsColumns[1], SearchDocumentsColumns[2], SearchDocumentsColumns[3]},
			},
			{
				Name:    "searchdocument_company_id_doc_date",
				Unique:  false,
				Columns: []*schema.Column{SearchDocumentsColumns[1], SearchDocumentsColumns[11]},
			},
			{
				Name:    "searchdocument_company_id_entity_type_doc_number",
				Unique:  false,
				Columns: []*schema.Column{SearchDocumentsColumns[1], SearchDocumentsColumns[2], SearchDocumentsColumns[4]},
			},
			{
				Name:    "searchdocument_company_id_entity_type_status",
				Unique:  false,
				Columns: []*schema.Column{SearchDocumentsColumns[1], SearchDocumentsColumns[2], SearchDocumentsColumns[14]},
			},
		},
	}
	// SearchRecentQueriesColumns holds the columns for the "search_recent_queries" table.
	SearchRecentQueriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "company_id", Type: field.TypeUint},
		{Name: "query", Type: field.TypeString, Size: 2147483647},
		{Name: "queried_at", Type: field.TypeTime},
	}
	// SearchRecentQueriesTable holds the schema information for the "search_recent_queries" table.
	SearchRecentQueriesTable = &schema.Table{
		Name:       "search_recent_queries",
		Columns:    SearchRecentQueriesColumns,
		PrimaryKey: []*schema.Column{SearchRecentQueriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "searchrecentquery_user_id_company_id_queried_at",
				Unique:  false,
				Columns: []*schema.Column{SearchRecentQueriesColumns[1], SearchRecentQueriesColumns[2], SearchRecentQueriesColumns[4]},
			},
		},
	}
	// SearchUsageStatsColumns holds the columns for the "search_usage_stats" table.
	SearchUsageStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "company_id", Type: field.TypeUint},
		{Name: "entity_type", Type: field.TypeString, Size: 32},
		{Name: "entity_id", Type: field.TypeUint},
		{Name: "click_count", Type: field.TypeInt, Default: 0},
		{Name: "last_clicked_at", Type: field.TypeTime},
	}
	// SearchUsageStatsTable holds the schema information for the "search_usage_stats" table.
	SearchUsageStatsTable = &schema.Table{
		Name:       "search_usage_stats",
		Columns:    SearchUsageStatsColumns,
		PrimaryKey: []*schema.Column{SearchUsageStatsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "searchusagestat_company_id_entity_type_entity_id",
				Unique:  true,
				Columns: []*schema.Column{SearchUsageStatsColumns[1], SearchUsageStatsColumns[2], SearchUsageStatsColumns[3]},
			},
			{
				Name:    "searchusagestat_company_id_entity_type",
				Unique:  false,
				Columns: []*schema.Column{SearchUsageStatsColumns[1], SearchUsageStatsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SearchDocumentsTable,
		SearchRecentQueriesTable,
		SearchUsageStatsTable,
	}
)

func init() {
	SearchDocumentsTable.Annotation = &entsql.Annotation{
		Table: "search_documents",
	}
	SearchRecentQueriesTable.Annotation = &entsql.Annotation{
		Table: "search_recent_queries",
	}
	SearchUsageStatsTable.Annotation = &entsql.Annotation{
		Table: "search_usage_stats",
	}
}
