// Code generated by ent, DO NOT EDIT.

package searchrecentquery

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the searchrecentquery type in the database.
	Label = "search_recent_query"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCompanyID holds the string denoting the company_id field in the database.
	FieldCompanyID = "company_id"
	// FieldQuery holds the string denoting the query field in the database.
	FieldQuery = "query"
	// FieldQueriedAt holds the string denoting the queried_at field in the database.
	FieldQueriedAt = "queried_at"
	// Table holds the table name of the searchrecentquery in the database.
	Table = "search_recent_queries"
)

// Columns holds all SQL columns for searchrecentquery fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCompanyID,
	FieldQuery,
	FieldQueriedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQueriedAt holds the default value on creation for the "queried_at" field.
	DefaultQueriedAt func() time.Time
)

// OrderOption defines the ordering options for the SearchRecentQuery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCompanyID orders the results by the company_id field.
func ByCompanyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyID, opts...).ToFunc()
}

// ByQuery orders the results by the query field.
func ByQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuery, opts...).ToFunc()
}

// ByQueriedAt orders the results by the queried_at field.
func ByQueriedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueriedAt, opts...).ToFunc()
}
